services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: a0618
      POSTGRES_DB: DateCalculatorDatabase


volumes:
  pgdata: